### PR TITLE
Add cancelUrl & returlUrl in PaymentOrder

### PR DESCRIPTION
**Pull request by tbordinat**
I have absolutely no idea if you are open source or not, I just wanna save somewhere useful my last modifications on the PayGreen PHP SDK.

It works, I use it for my PH-22481 Jira ticket still pending.

### CODE REVIEW

**Comment by guillaumbertin** [comment]
Hi @tbordinat,

**Thanks** for your contribution.
In addition, can you complete your adds with somes behat and unit tests?

- For behat:

In fetaures/bootsrap/PaymentOrderDictionnary.php 

**aPaymentOrderObject function**, add at the end: 
$this->paymentOrder->setCancelUrl('https://www.my-cancel-url.com');
$this->paymentOrder->setReturnUrl('https://www.my-return-url.com');

**iReceiveAResponseWithThePaymentOrder function**, for test the result:
Assert::assertEquals($this->paymentOrder->getCancelUrl() . '?po_id=' . $data->id, $data->cancel_url);
Assert::assertEquals($this->paymentOrder->getReturnUrl() . '?po_id=' . $data->id, $data->return_url);


- And for unit tests:

In tests/Unit/Payment/V3/ClientTest.php

**testRequestCreatePaymentOrder function**:

...
$paymentOrder->setCancelUrl('https://www.monsite.com/cancel');
$paymentOrder->setReturnUrl('https://www.monsite.com/return');

...
$this->assertEquals($paymentOrder->getCancelUrl(), 'https://www.monsite.com/cancel');
$this->assertEquals($paymentOrder->getReturnUrl(), 'https://www.monsite.com/return');


Kind regards

**Comment by tbordinat** [comment]
Unfortunately, my holidays are starting right now, I can't do anything until january 2nd.

I would also add this one to check the http query builder with URLs already containing parameters:

```
aPaymentOrderObject function, add at the end:
$this->paymentOrder->setCancelUrl('https://www.my-cancel-url.com?cancel');
$this->paymentOrder->setReturnUrl('https://www.my-return-url.com?return');

iReceiveAResponseWithThePaymentOrder function, for test the result:
Assert::assertEquals($this->paymentOrder->getCancelUrl() . '?cancel&po_id=' . $data->id, $data->cancel_url);
Assert::assertEquals($this->paymentOrder->getReturnUrl() . '?return&po_id=' . $data->id, $data->return_url);
```

Do you think you can commit on this PR?

Bonnes fêtes de Noël ! :-D

**Comment by guillaumbertin** [comment]
Hi Thomas,

I can't commit on your branch, we can settle this when you return.

Passez de bonnes fêtes :)

**Comment by tbordinat** [comment]
Hi !
I can't re-run tests, but I think it's ok now
Thomas

**Comment by tbordinat** [comment]
Hi @guillaumbertin is there any log for the failing behat test?

I don't understand why it fails

**Comment by guillaumbertin** [comment]
Hi Thomas,

Thank you for your contribution.
For Behat, I will check, when you run the command `docker-compose exec php vendor/bin/behat ` you have no result ?

**Comment by tbordinat** [comment]
> Hi Thomas,
> 
> Thank you for your contribution. For Behat, I will check, when you run the command `docker-compose exec php vendor/bin/behat ` you have no result ?

Hi Guillaume!

Thx for your answer!
I didn't install the project, I first created my PR from GitHub without cloning anything.
I developped the fix in my own environment, and tested it with my project, so tests are only running on GitHub, I thought I would have some logs to help but no.

Thank you for handling it on your side!

**Comment by tbordinat** [comment]
image

I'm sorry, I don't have the time to go on this further.

But thank you, it can be interesting to see how you build your environment for Paygreen, we also use docker-compose as well :smirk:

**Review by guillaumbertin — APPROVED** [review]

**Pull request merged**
